language: go
go:
- 1.12.x
cache: bundler
before_install:
- go get github.com/antonholmquist/jason
- go get github.com/aws/aws-lambda-go/events
- go get github.com/aws/aws-lambda-go/lambda
- go get github.com/aws/aws-sdk-go/aws
- go get github.com/aws/aws-sdk-go/aws/credentials
- go get github.com/aws/aws-sdk-go/aws/session
- go get github.com/aws/aws-sdk-go/aws/signer/v4
- go get github.com/aws/aws-sdk-go/service/s3/s3manager
- go get github.com/sha1sum/aws_signing_client
- go get gopkg.in/olivere/elastic.v6
install: 
script:
- go test -v -cover sendlog_test.go sendlog.go

env:
  global:
    secure: PkKRXc9diXLG2hVGYhHEjQGJoVl+xmm3lHIyp98/dgNrZtC3qlvszkqIAJukK0e0HGo3A+Spib1Vq0ZVjKlH57thedJM6+rTDY3fPChl9sfuOdP3VF6ZiCsL6AOEOEQ74BTbltvCF1nZ/jhBsy212cZ8p9Y7RTa3Eb5RMwBBsNaQqNSjgz3RSSsRE3yxlmKhcfpOcVLbspI7pEURnIkky2Ru903jQR1dVqTPrJxMewXDdPeXKXeX5oRa4a4LhQBnLVzzRSllrRZ8yBgYOqj7ZupiRZAmINWLPd6RmtPGywRmMJS97OiE05c8Vn3W4gSZb0zIQh2iLNm7x+VXbDukqezGeq2TkAyf1ZAT1ULZMmRxNTysP1EAil3Wljte2RMWuOKEm2s4DcqNuzZ6yzPhGslepJbQmvwWPKbZ4LEv4OXqc0dmqfe0YsZuf092TOj/1sXHdS+IVvbIOVe9Sx/gZ3AW4/JOCuRIXDenBPJjb7tKHywriIT5xSQEXVxaXlRdQ8CmPPqN6RX7r4tKt+g/YN4gBYIEU3dJs8icq8/LbjzFFJG5Bu6d+Oub6sjSWnLyFnN2RYRMpI7TxnoZcVrQudj/bwETzTSOI1r4ybIC/j6Hc5mC9WWQYL8B80iZ8C+ieoqwrp7vAcCeHewWXhGzvuT8vmKkc4hf3n8kMSOsaDA=
